// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PieShop.API.DbContexts;

#nullable disable

namespace PieShop.API.Migrations
{
    [DbContext(typeof(PieShopContext))]
    partial class PieShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PieShop.API.Entities.Pie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Our famous apple pie",
                            Name = "Apple Pie",
                            Price = 12.949999999999999
                        },
                        new
                        {
                            Id = 2,
                            Description = "A delicious pie filled with succulent blueberries",
                            Name = "Blueberry Pie",
                            Price = 12.949999999999999
                        },
                        new
                        {
                            Id = 3,
                            Description = "A decadent, creamy cheesecake",
                            Name = "Cheesecake",
                            Price = 14.949999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
